### ISSUE TITLE
blockchain blocks of niobio-cash

### ISSUE THREAD

**Issue by blackunixteam** [quan-projects/quan-node#54]
Poderia atualizar os arquivos de blocos da blockchain do niobio-cash?? só tem até 2018, e pra baixar ta osso, muito lento, vai demorar meses

**Comment by jamilservicos** [comment]
acredito que sua duvida ja foi respondida no grupo.
mas caso não... use o node remote, para atualizar. também veja em release a versao mais atualizada para o seu sistema.
